zookeeper:
        image: 'jplock/zookeeper:3.4.6'
        ports:
          - '2181:2181'
kafka:
        image: 'ches/kafka'
        links:
          - zookeeper:zookeeper
        ports:
          - "9092:9092"
cassandra:
        image: 'cassandra:2.2.4'
        volumes:
          - /usr/local/cassandra:/var/lib/cassandra
        ports:
          - "9042:9042"
