zookeeper:
        image: 'jplock/zookeeper:3.4.6'
        ports:
          - '2181:2181'

dynamodb:
        image: rajatvig/dynalite-alpine
        ports:
          - '8000:8000'
##
datastore:
        image: 'mastodonc/kixi.datastore:latest'
        #use volumes_from until we upgrade and get depends_on
        ports:
          - "8080:8080"
        volumes_from:
          - "dynamodb"
        links:
          - zookeeper:zookeeper
          - dynamodb:dynamodb
        environment:
          - CONFIG_PROFILE=local
          - ZOOKEEPER=zookeeper
          - DYNAMODB=http://dynamodb:8000
          - COMMAND_STREAM=witan-dev-command
          - EVENT_STREAM=witan-dev-event
          - ENVIRONMENT=local
        env_file:
          - aws-variables.env

heimdall:
        image: 'mastodonc/kixi.heimdall-dev:latest'
        ports:
          - "3002:3002"
        volumes_from:
          - "dynamodb"
        links:
          - zookeeper:zookeeper
          - dynamodb:dynamodb
        environment:
          - ZOOKEEPER=zookeeper
        env_file:
          - aws-variables.env
